spring:
  cloud:
    gateway:
      routes:
        - id: products-api
          uri: lb://products-api
          predicates:
            - Path=/api1/**

        - id: orders-api
          uri: lb://orders-api
          predicates:
            - Path=/api2/**

        - id: customer-api
          uri: lb://customer-api
          predicates:
            - Path=/api3/**

        - id: admin-api
          uri: lb://admin-api
          predicates:
            - Path=/api4/**

        - id: notifications-api
          uri: lb://notifications-api
          predicates:
            - Path=/api5/**
server:
  port: 8081