spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ashokit_ecommerce
    username: root
    password: manager
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ombolanwar5@gmail.com
    password: ehwq dhfi fegq bhbv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  boot:
    admin:
      client:
        url: http://localhost:1111

server:
  port: 7075
  servlet:
    context-path: /api5

management:
  endpoints:
    web:
      exposure:
        include: "*"
        